# Built with Jekyll 3.2.0

# Setup
title:               DCP Reading Editions
tagline:             'Plain Text Reading Editions of Works Written by Margaret Cavendish, Duchess of Newcastle (1623-1673)'
description:         'These editions are supported by Ed. Ed is a Jekyll theme designed for textual editors based on minimal computing principles, and focused on legibility and flexibility.'
url:                 'http://digicavendish.github.io'
baseurl:             '/ed'

# About/contact
author:
  name:              Shawn W. Moore
  url:               https://twitter.com/S_moores
  email:             digitalcavendishproject@gmail.com

# Permalinks

permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  texts:
    output: true

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Exclusions from the final site
exclude:
  - optional
  - vendor

# Theme
theme: jekyll-theme-slate


